apiVersion: v1
kind: Pod
metadata:
  name: test-webhook-pod1
  labels:
    app: admission-webhook-example
spec:
  containers:
  - name: admission-webhook-example
    image: dfy007/admission-webhook-example:v1.3
    imagePullPolicy: IfNotPresent
    env:
      - name: WHITELIST_REGISTRIES
        value: docker.io,gcr.io
    ports:
      - containerPort: 443
    volumeMounts:
      - name: webhook-certs
        mountPath: /etc/webhook/certs
        readOnly: true
  volumes:
    - name: webhook-certs
      hostPath:
        path: /test/data