apiVersion: v1
kind: ServiceAccount
metadata:
  name: admission-registry-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: admission-registry-role
rules:
  - verbs: ["*"]
    resources: ["validatingwebhookconfigurations","mutatingwebhookconfigurations"]
    apiGroups: ["admissionregistration.k8s.io"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admission-registry-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admission-registry-role
subjects:
  - kind: ServiceAccount
    name: admission-registry-sa
    namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod1
spec:
  serviceAccount: admission-registry-sa
  containers:
    - name: webhook-init
      image: dfy007/admission-registry-tls:v1.6
      imagePullPolicy: IfNotPresent
      env:
        - name: WEBHOOK_NAMESPACE
          value: default
        - name: WEBHOOK_SERVICE
          value: admission-registry
        - name: VALIDATE_CONFIG
          value: admission-registry-validate
        - name: MUTATE_CONFIG
          value: admission-registry-mutate
        - name: VALIDATE_PATH
          value: /validate
        - name: MUTATE_PATH
          value: /mutate
      volumeMounts:
        - name: webhook-certs
          mountPath: /etc/webhook/certs
  volumes:
    - name: webhook-certs
      hostPath:
        path: /test/data